spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_flow_dev
    username: erickbarrosrezende
    password: 0123456789

  flyway:
    schemas: finance_flow_api
    default-schema: finance_flow_api

  h2:
    console:
      enabled: false
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: finance_flow_api
